services:
  backend:
    image: capcom6/sms-gateway
    build:
      context: .
      dockerfile: build/package/Dockerfile
      args:
        - APP=sms-gateway
    environment:
      - DEBUG=
      - CONFIG_PATH=config.yml
      - GOOSE_DBSTRING=root:AEPMa17pu84Va7EPxeNOTKLGkQTvAvfQbHNasjFYAgzU1gl7Hyjxbt9y5ZTX5897@tcp(wkoo0ggowk080cg04g0kw8kw:3306)/asg
      - HTTP__LISTEN=0.0.0.0:3000
      - DATABASE__HOST=db
      - DATABASE__PORT=3306
      - DATABASE__USER=sms
      - DATABASE__PASSWORD=sms
      - DATABASE__DATABASE=sms
    ports:
      - "3010:3000"
    volumes:
      - ./config.yml:/app/config.yml:ro
    restart: 'unless-stopped'

